# https://yarnpkg.com/configuration/yarnrc

# If false, SSL certificate errors will be ignored
enableStrictSsl: true

# Plug'n'Play
nodeLinker: node-modules

# Defines the authentication credentials to use by default when accessing your registries (equivalent to _auth in the v1). This settings is strongly discouraged in favor of npmAuthToken.
# npmAuthIdent: "username:password"

# Defines the authentication credentials to use by default when accessing your registries (equivalent to _authToken in the v1). If you're using npmScopes to define multiple registries, the npmRegistries dictionary allows you to override these credentials on a per-registry basis.
# npmAuthToken: "ffffffff-ffff-ffff-ffff-ffffffffffff"

# Defines the default access to use when publishing packages to the npm registry. Valid values are public and restricted, but restricted usually requires to register for a paid plan (this is up to the registry you use).
# npmPublishAccess: "public"

# Defines the registry that must be used when pushing packages. Doesn't need to be defined, in which case the value of npmRegistryServer will be used. Overridden by publishConfig.registry.
# npmPublishRegistry: "https://npm.pkg.github.com"

# yarn v3 does not recognize .npmrc.
# @commentgeneratorcollection:registry = https://npm.pkg.github.com
npmScopes:
  commentgeneratorcollection:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: <your-token>

unsafeHttpWhitelist:
  - "*.example.org"
  - "example.org"
