name: Electronegativity

on:
  push:
    branches: [ develop ]
#    branches-ignore:
#      - dependabot/**
#      - renovate/**

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install corepack
        run: |
          npm uninstall -g yarn pnpm
          npm install -g corepack

      - name: Configure
        run: npm config set '//npm.pkg.github.com/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: CommentGeneratorCollection/electronegativity-action@develop
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ../results
