name: Electronegativity

on:
  push:
    branches: [ develop ]
#    branches-ignore:
#      - dependabot/**
#      - renovate/**

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install corepack
        run: |
          npm uninstall -g yarn pnpm
          npm install -g corepack

      - uses: CommentGeneratorCollection/electronegativity-action@v1
        env:
          PAT: ${{secrets.PAT}}

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ../results
